version: '3.8'

services:
  dsr-db:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=dsrdb
    volumes:
      - dsr-pg:/bitnami/postgresql

  # dsr-api:
  #   build: .
  #   ports:
  #     - '3333:3333'
  #   environment:
  #     - JWT_SECRET=${JWT_SECRET}
  #     - DATABASE_URL=${DATABASE_URL}
  #   depends_on:
  #     - dsr-db
  #   restart: always
    
volumes:
    dsr-pg:

